_target_: src.model.conformer.Conformer
n_feats: ${common.n_mels}
n_tokens: 28
d_model: 256              # Размер скрытого слоя
n_layers: 8               # Количество блоков
n_head: 4                 # Количество голов attention
conv_kernel_size: 31      # Размер ядра свертки
dropout: 0.1
