sample_rate: 16000  # частота дискретизации
n_fft: 512          # число точек fft: шаг по частоте = sample_rate / n_fft = 16000 / 512 = 31,25 Гц на бин
win_length: 400     # длина окна stft в семплах, 400 / 16000 = 0,025 c
hop_length: 160     # шаг между окнами stft, 160 / 16000 = 0,01 c
n_mels: 64          # число мел-фильтров, размерность по частоте
f_min: 0            # нижняя граница частот
f_max: 8000         # верхняя граница частот