defaults:
  - common
  - model: deepspeech
  - datasets: custom_dir
  - dataloader: default
  - metrics: asr
  - transforms: no_augs
  - _self_

text_encoder:
  _target_: src.text_encoder.CTCTextEncoder

decoding:
  beam_size: 10
  topk_per_timestep: 50
  beam_threshold: 100.0

inferencer:
  device: auto
  save_path: "inference_outputs"
  from_pretrained: "saved/model_best.pth"
  seed: 42
