get_spectrogram:
  _target_: torchaudio.transforms.MelSpectrogram
  sample_rate: 16000
  n_fft: 1024
  win_length: 1024
  hop_length: 256
  f_min: 0
  f_max: 8000
  n_mels: 128

audio:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: src.transforms.wav_augs.gain.Gain
      p: 0.5
    - _target_: src.transforms.wav_augs.speed_perturb.SpeedPerturb
      p: 0.3
      sample_rate: 16000
      speeds: [0.9, 1.0, 1.1]
    - _target_: src.transforms.wav_augs.colored_noise.ColoredNoise
      p: 0.2
      sample_rate: 16000
      snr_db: [5, 25]
      alpha: [0.0, 1.0, 2.0]

spectrogram:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: src.transforms.Log
      eps: 1e-5
    - _target_: src.transforms.PerUtteranceCMVN
      out_mean: 0.0
      out_std: 1.0
